# Generated by Django 2.2.7 on 2019-12-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('education', models.TextField()),
                ('personal_info', models.TextField()),
                ('projects', models.TextField()),
                ('technical_skill', models.TextField()),
                ('language', models.TextField()),
                ('awards', models.TextField()),
                ('membership', models.TextField()),
                ('interest', models.TextField()),
                ('hobbies', models.TextField()),
                ('personal_qualities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('candidate_user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirm_pass', models.CharField(max_length=200)),
                ('picture_user', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecruterRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirm_pass', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_url', models.URLField()),
                ('Profile_Pic', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
