# Generated by Django 2.2.7 on 2019-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191210_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
