# Generated by Django 2.2.7 on 2019-12-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_candidateprofile_candidateregistration_category_recruterregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CandidateRegistration', to='social.Category'),
            preserve_default=False,
        ),
    ]
