# Generated by Django 2.2.7 on 2019-12-08 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_candidateprofile_candidate_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='candidate_category_id',
            new_name='candidate_category',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
