# Generated by Django 2.2.7 on 2019-12-10 06:02

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('social', '0003_auto_20191210_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tech_skill',
            field=models.ManyToManyField(to='social.Skills'),
        ),
    ]
