# Generated by Django 2.2.7 on 2019-12-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191209_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateRegistration',
        ),
        migrations.DeleteModel(
            name='TestName',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='personal_qualities',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='technical_skill',
        ),
        migrations.AlterField(
            model_name='recruterregistration',
            name='Profile_Pic',
            field=models.ImageField(upload_to='Recruter'),
        ),
    ]
