# Generated by Django 2.2.7 on 2019-12-10 06:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('social', '0004_auto_20191210_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='tech_skill',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
