# Generated by Django 2.2.7 on 2019-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20191210_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(default=' add ', max_length=250),
            preserve_default=False,
        ),
    ]
