# Generated by Django 2.2.7 on 2019-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_candidateprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
