# Generated by Django 2.2.7 on 2019-12-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20191210_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
