# Generated by Django 2.2.7 on 2019-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_candidateprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
